project:
  type: website

website:
  title: "Shrividya Ravi"
  navbar:
    right:
      - icon: github
        href: https://github.com/shriv
      - icon: twitter
        href: https://twitter.com/ShrividyaRavi
    left:
      - text: "About"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "Articles"
        file: articles.qmd
      - text: "Technical blog"
        file: blog.qmd
      - text: "Presentations"
        file: talks.qmd

format:
  html:
    theme: cosmo
    css: styles.css