---
title: "RAPping in the public sector (in 5 minutes)"
event: "Innovations in Applied Data Symposium"
date: 2021-06-03
---

Straggling legacy SAS scripts requiring manual steps are a common \"feature\" of data processing tasks in the public sector. However, refactoring such scripts to modern, reproducible analytical pipelines (RAP) can be challenging due to a lack of IT infrastructure or high complexity. In such situations, interim solutions can at least reduce manual effort and mental overhead. One such solution is using Python as an effective glue to create one click execution pipelines. Manual tasks like downloading data from email, updating new data file names in scripts, running scripts in sequence and more, can be managed with Python and its rich ecosystem of packages. In this talk, I will showcase how three Python packages, exchangelib, jupyter and saspy, can create quick and easy automated versions of legacy SAS scripts that contain many types of manual steps.

<a href="https://github.com/shriv/applied-data-conf-21-preso/blob/master/presentation.pdf" class="btn btn-primary">**Slides**</a> <a href="https://www.youtube.com/watch?v=D5eCVZXq96A&t=1770s" class="btn btn-primary">**Video**</a> 