---
title: "WORKSHOP: Analysing geospatial connectivity to understand a city"
event: "FOSS4G SoTM Oceania"
date: 2019-11-12
---

Static or interactive maps can reveal useful patterns and insights. For example, layering accident locations on a basemap can highlight hotspots of poor road safety. These simple data overlays can be extended to an integrated analysis with the road network for deeper insight - like accident hotspots on road segments that bottleneck commuter flows. As denizens of a city we primarily interact with the built urban environment via its streets, roads and paths. Hence, intuitive questions of the 'Urban Experience' must involve the geospatial road network. 

In this workshop, we'll use Python and the packages, osmnx and pandana, to characterise Wellington: the cool little capital of New Zealand with a unique topography. Using omsnx, pandana and data of the built environment (from OpenStreetMap and Wellington City Council open data), we can quantify how Wellington functions as a city.

<a href="https://github.com/shriv/foss4g-workshop/blob/master/notebooks/applications.ipynb" class="btn btn-primary">**Workshop material**</a> <a href="https://github.com/shriv/foss4g-workshop" class="btn btn-primary">**Code**</a>